kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.production.name | default .Values.name  }}
  namespace: {{ .Values.production.namespace | default "production" }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
{{ .Values.production.nginxConfig | default .Values.nginxConfig | indent 6 }}
spec:
  tls:
  - secretName: {{ .Values.production.name | default .Values.name  }}-tls
    hosts:
    - {{ .Values.production.domain | default .Values.domain }}
    - www.{{ .Values.production.domain | default .Values.domain }}
  rules:
  - host: {{ .Values.production.domain | default .Values.domain }}
    http: &http_service
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.production.name | default .Values.name  }}
          servicePort: {{ .Values.production.port | default .Values.port | default 80 }}

  # Alias domains
  - host: www.{{ .Values.production.domain | default .Values.domain }}
    http: *http_service
