{{ include "values-overwrite" . }}

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ required "A valid name entry required!" .FinalValues.name }}
  namespace: {{ .Values.production.namespace | default "production" }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .FinalValues.nginxConfig }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- .FinalValues.nginxConfig | nindent 6 -}}
    {{- end }}
spec:
  tls:
  - secretName:
    {{- if .FinalValues.tlsSecretName }}
      {{ .FinalValues.tlsSecretName }}
    {{- else }}
      {{ required "A valid name entry required!" .FinalValues.name }}-tls
    {{- end }}
    hosts:
      - {{ required "A valid domain entry required!" .FinalValues.domain }}
    {{- if .FinalValues.addWwwPrefixHost }}
      - www.{{ required "A valid domain entry required!" .FinalValues.domain }}
    {{- end }}

    {{- range $host := .FinalValues.extraHosts }}
    {{- if not ($host.tlsSecret) }}
      - {{ $host.domain }}
    {{- end }}
    {{- end }}

  {{- range $host := .FinalValues.extraHosts }}
  {{- if $host.tlsSecret }}
  - secretName: {{ $host.tlsSecret }}
    hosts:
      - {{ $host.domain }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ required "A valid domain entry required!" .FinalValues.domain }}
    http: &http_service
      paths:
      - path: /
        backend:
          serviceName: {{ required "A valid name entry required!" .FinalValues.name }}
          servicePort: {{ .FinalValues.port | default 80 }}

  {{- if .FinalValues.addWwwPrefixHost }}
  # Alias domains
  - host: www.{{ required "A valid domain entry required!" .FinalValues.domain }}
    http: *http_service
  {{- end }}

  {{- range $host := .FinalValues.extraHosts }}
  - host: {{ $host.domain }}
    http: *http_service
  {{- end }}
