{{- $data := mergeOverwrite .Values .Values.production -}}

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ required "A valid name entry required!" $data.name }}
  namespace: {{ .Values.production.namespace | default "production" }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if $data.nginxConfig }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- $data.nginxConfig | nindent 6 -}}
    {{- end }}
spec:
  tls:
  - secretName: {{ required "A valid name entry required!" $data.name }}-tls
    hosts:
    - {{ required "A valid domain entry required!" $data.domain }}
    {{- if $data.addWwwPrefixHost }}
    - www.{{ required "A valid domain entry required!" $data.domain }}
    {{- end }}
  {{- range $data.extraDomains }}
  - secretName: {{ .name }}-tls
    hosts:
      {{- range $host := .hosts }}
      - {{ $host }}
      {{- end }}
  {{- end }}
  rules:
  - host: {{ required "A valid domain entry required!" $data.domain }}
    http: &http_service
      paths:
      - path: /
        backend:
          serviceName: {{ required "A valid name entry required!" $data.name }}
          servicePort: {{ $data.port | default 80 }}

  {{- if $data.addWwwPrefixHost }}
  # Alias domains
  - host: www.{{ required "A valid domain entry required!" $data.domain }}
    http: *http_service
  {{- end }}

  {{- range $data.extraDomains }}
  {{- range $host := .hosts }}
  - host: {{ $host }}
    http: *http_service
  {{- end }}
  {{- end }}
