{{ include "values-overwrite" . }}

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ if .Values.staging.name }}{{ .Values.staging.name }}{{ else }}staging-{{ .Values.name }}{{ end }}
  namespace: {{ .Values.staging.namespace | default "staging" }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .FinalValues.nginxConfig }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{- .FinalValues.nginxConfig | nindent 6 }}
    {{- end }}
spec:
  tls:
  - secretName: {{ if .Values.staging.name }}{{ .Values.staging.name }}{{ else }}staging-{{ .Values.name }}{{ end }}-tls
    hosts:
    {{- if .Values.staging.domain }}
      - {{ .Values.staging.domain }}
      {{- if .FinalValues.addWwwPrefixHost }}
      - www.{{ .Values.staging.domain }}
      {{- end }}
    {{- else }}
      - staging.{{ .Values.domain }}
      {{- if .FinalValues.addWwwPrefixHost }}
      - www.staging.{{ .Values.domain }}
      {{- end }}
    {{- end }}

    {{- range $host := .FinalValues.extraHosts }}
    {{- if not ($host.tlsSecret) }}
      - {{ $host.domain }}
    {{- end }}
    {{- end }}

  {{- range $host := .FinalValues.extraHosts }}
  {{- if $host.tlsSecret }}
  - secretName: {{ $host.tlsSecret }}
    hosts:
      - {{ $host.domain }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ if .Values.staging.domain }}{{ .Values.staging.domain }}{{ else }}staging.{{ .Values.domain }}{{end}}
    http: &http_service
      paths:
      - path: /
        backend:
          serviceName: {{ required "A valid name entry required!" .Values.name }}
          servicePort: {{ .FinalValues.port | default 80 }}

  {{- if .FinalValues.addWwwPrefixHost }}
  # Alias domains
  - host: www.{{ if .Values.staging.domain }}{{ .Values.staging.domain }}{{ else }}staging.{{ .Values.domain }}{{end}}
    http: *http_service
  {{- end }}

  {{- range $host := .FinalValues.extraHosts }}
  - host: {{ $host.domain }}
    http: *http_service
  {{- end }}
