kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ if .Values.staging.name }}{{ .Values.staging.name }}{{ else }}staging-{{ .Values.name }}{{ end }}
  namespace: {{ .Values.staging.namespace | default "staging" }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
{{ .Values.staging.nginxConfig | default .Values.nginxConfig | indent 6 }}
spec:
  tls:
  - secretName: {{ if .Values.staging.name }}{{ .Values.staging.name }}{{ else }}staging-{{ .Values.name }}{{ end }}-tls
    hosts:
    {{ if .Values.staging.domain }}
      - {{ .Values.staging.domain }}
      - www.{{ .Values.staging.domain }}
    {{ else }}
      - staging.{{ .Values.domain }}
      - www.staging.{{ .Values.domain }}
    {{ end }}
  rules:
  - host: {{ if .Values.staging.domain }}{{ .Values.staging.domain }}{{ else }}staging.{{ .Values.domain }}{{end}}
    http: &http_service
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.staging.name | default .Values.name }}
          servicePort: {{ .Values.staging.port | default .Values.port | default 80 }}

  # Alias domains
  - host: www.staging.{{ .Values.staging.name | default .Values.name }}
    http: *http_service
